version: 1.9.{build}.0

assembly_info:
  patch: true
  file: AssemblyVersion.cs
  assembly_version: "1.9.0.0"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

build:
  project: src\SqlLocalDb.msbuild
  verbosity: minimal

artifacts:
  - path: src\BuildOutput\*.nupkg
  - path: src\BuildOutput\*.zip
